// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH7MwgxxMpXyfeg4F806OONgY6Lfa9NNg',
    appId: '1:627071554501:web:24ae285a9f8a0f030471ac',
    messagingSenderId: '627071554501',
    projectId: 'projectsmanagement-4374d',
    authDomain: 'projectsmanagement-4374d.firebaseapp.com',
    storageBucket: 'projectsmanagement-4374d.firebasestorage.app',
    measurementId: 'G-JHG5GK8R8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIL1S1sYnFQ2PSPEvUgsMFVkKHnCWSDQA',
    appId: '1:627071554501:android:64427206ea1f91990471ac',
    messagingSenderId: '627071554501',
    projectId: 'projectsmanagement-4374d',
    storageBucket: 'projectsmanagement-4374d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtXw8gklFwVGjqQapv-dfiwjwAQjKgasE',
    appId: '1:627071554501:ios:f89628688bc8aae20471ac',
    messagingSenderId: '627071554501',
    projectId: 'projectsmanagement-4374d',
    storageBucket: 'projectsmanagement-4374d.firebasestorage.app',
    iosBundleId: 'com.example.kanbanBoardTest',
  );
}
